name: Testing workflow Varibles

on:
  workflow_dispatch

env:
  cloud: Azure_cloud

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. is using $cloud!"
        env:
          First_Name: OmPrakash
